# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\" \n\x0fInternalRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\x10InternalResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2N\n\x0eInternalServer\x12<\n\x05Query\x12\x17.server.InternalRequest\x1a\x18.server.InternalResponse\"\x00\x42\x1dZ\x1bgithub.com/intx4/pir/serverb\x06proto3')



_INTERNALREQUEST = DESCRIPTOR.message_types_by_name['InternalRequest']
_INTERNALRESPONSE = DESCRIPTOR.message_types_by_name['InternalResponse']
InternalRequest = _reflection.GeneratedProtocolMessageType('InternalRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.InternalRequest)
  })
_sym_db.RegisterMessage(InternalRequest)

InternalResponse = _reflection.GeneratedProtocolMessageType('InternalResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:server.InternalResponse)
  })
_sym_db.RegisterMessage(InternalResponse)

_INTERNALSERVER = DESCRIPTOR.services_by_name['InternalServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033github.com/intx4/pir/server'
  _INTERNALREQUEST._serialized_start=24
  _INTERNALREQUEST._serialized_end=56
  _INTERNALRESPONSE._serialized_start=58
  _INTERNALRESPONSE._serialized_end=92
  _INTERNALSERVER._serialized_start=94
  _INTERNALSERVER._serialized_end=172
# @@protoc_insertion_point(module_scope)
